apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dd-api-key
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: dd-api-key
    template:
      type: Opaque
  data:
  - secretKey: api-key
    remoteRef:
      key: api-key
