receivers:
  jaeger:
    protocols:
      thrift_compact:
        endpoint: "0.0.0.0:6831"
      thrift_binary:
        endpoint: "0.0.0.0:6832"

exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
      site: ${DD_SITE}

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [datadog]
